### ISSUE TITLE
can you made some settings?

### ISSUE THREAD

**Issue by scriptcuddle** [hyPnOtICDo0g/rss-chan#10] opened 2022-01-13 05:30 UTC
1. just link
2. title + torrent link
3. title + torrent link + detail

such as this
https://telegra.ph/file/aaf01b278ef1b0cc225d4.png

**Comment by hyPnOtICDo0g** [comment] 2022-01-13 05:57
Duplicate of #2.

**Closed as completed by hyPnOtICDo0g** 2022-01-13 05:57 UTC
